### PR TITLE
[FTR] Update code style and pom

### PR DESCRIPTION
**Pull request by julianfrancor**
## Pull Request Checklist

Please review and check the following before merging this pull request:

- [x] **Code Review**: Have you reviewed your code for any potential issues or improvements?
- [x] **Local Testing**: Have you tested the changes locally to ensure they work as expected?
- [x] **Unit Tests**: Have you added or updated unit tests to cover the changes made?
- [x] **Documentation**: Have you updated any relevant documentation to reflect the changes?

### Additional Notes (if any)

[Add any additional information or notes about the changes made, or specific areas that may need extra attention.]

---

By submitting this pull request, I confirm that my code is ready for review and meets the above checklist requirements.

David Roldán
Victor Muñoz
Julian Franco

CI/CD - EAFIT 2023

### CODE REVIEW

**Comment by julianfrancor** [comment]
|Overall Project|NaN% **`NaN%`**|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by julianfrancor** [comment]
|Overall Project|NaN% **`NaN%`**|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by julianfrancor** [comment]
# :lobster: Coverage Report
|Overall Project|NaN% **`NaN%`**|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by julianfrancor** [comment]
# :lobster: Coverage Report
|Overall Project|NaN% **`NaN%`**|:green_apple:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

**Comment by julianfrancor** [comment]
# :lobster: Coverage Report
|Overall Project|67.92% **`-4.72%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|0%|:x:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[Calculator.kt](https://github.com/julianfrancor/cicdapp-dvj/blob/e1b2bd57f49422af86c1d6fc71aeb0632cfbf548/src%2Fmain%2Fkotlin%2Fcom%2Feafit%2Fcalculatordvj%2Fmodel%2FCalculator.kt)|100%|:green_apple:|
|[CalculatorController.kt](https://github.com/julianfrancor/cicdapp-dvj/blob/e1b2bd57f49422af86c1d6fc71aeb0632cfbf548/src%2Fmain%2Fkotlin%2Fcom%2Feafit%2Fcalculatordvj%2Fcontroller%2FCalculatorController.kt)|69.57% **`-7.25%`**|:x:|

**Comment by julianfrancor** [comment]
# :lobster: Coverage Report
|Overall Project|67.92% **`-4.72%`**|:x:|
|:-|:-|:-:|
|Files changed|0%|:x:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[Calculator.kt](https://github.com/julianfrancor/cicdapp-dvj/blob/d80a1829279a91ca9b33fcb771f0b1b71eb7d246/src%2Fmain%2Fkotlin%2Fcom%2Feafit%2Fcalculatordvj%2Fmodel%2FCalculator.kt)|100%|:green_apple:|
|[CalculatorController.kt](https://github.com/julianfrancor/cicdapp-dvj/blob/d80a1829279a91ca9b33fcb771f0b1b71eb7d246/src%2Fmain%2Fkotlin%2Fcom%2Feafit%2Fcalculatordvj%2Fcontroller%2FCalculatorController.kt)|69.57% **`-7.25%`**|:x:|

**Comment by julianfrancor** [comment]
# :lobster: Coverage Report
|Overall Project|67.92% **`-4.72%`**|:x:|
|:-|:-|:-:|
|Files changed|0%|:x:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[Calculator.kt](https://github.com/julianfrancor/cicdapp-dvj/blob/0506b8b7358fc2e96419a30125e575cd5d1b4025/src%2Fmain%2Fkotlin%2Fcom%2Feafit%2Fcalculatordvj%2Fmodel%2FCalculator.kt)|100%|:green_apple:|
|[CalculatorController.kt](https://github.com/julianfrancor/cicdapp-dvj/blob/0506b8b7358fc2e96419a30125e575cd5d1b4025/src%2Fmain%2Fkotlin%2Fcom%2Feafit%2Fcalculatordvj%2Fcontroller%2FCalculatorController.kt)|69.57% **`-7.25%`**|:x:|

**Review by vmunozm — APPROVED** [review]
Breve

**Pull request merged**
